version: '3.8'

services:
  web:
    image: php:8.0-apache
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - db
    environment:
      - "DB_HOST=db"
      - "DB_USER=user"
      - "DB_PASSWORD=password"
      - "DB_NAME=miblog"
    # Instalación de dependencias al iniciar
    command: bash -c "docker-php-ext-install mysqli && apache2-foreground"
  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: miblog
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

  # --- NUEVO SERVICIO: PHPMYADMIN ---
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "8081:80"  # Accederás por el puerto 8081
    environment:
      PMA_HOST: db            # Nombre del servicio mysql de arriba
      PMA_USER: user          # Usuario definido en db
      PMA_PASSWORD: password  # Contraseña definida en db
    depends_on:
      - db

volumes:
  db_data: